apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 3
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: yul.ocir.io/ax7qiwwaer3v/spring-apps/spring-server:1
        imagePullPolicy: Always
        ports:
        - name: app
          containerPort: 8091
          protocol: TCP
      imagePullSecrets:
        - name: ocispring
---
apiVersion: v1
kind: Service
metadata:
  name: spring-app-lb
  labels:
    app: app
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "100"
spec:
  type: LoadBalancer
  ports:
  - port: 8091
  selector:
    app: app
